-- drop tables
drop table if exists booking cascade;
drop table if exists event cascade;
drop table if exists seat cascade;

-- create tables
create table booking (
    expires_at timestamp(6),
    reserved_at timestamp(6),
    seat_id bigint,
    id uuid not null,
    payment_id varchar(255),
    payment_intent_id varchar(255),
    status varchar(255) check (status in ('PENDING','INCOMPLETE','CONFIRMED','EXPIRED','FAILED')),
    user_id varchar(255),
    primary key (id)
);

create table event (
    price float(53) not null,
    total_seats integer not null,
    date timestamp(6),
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table seat (
    event_id bigint not null,
    id bigint generated by default as identity,
    version bigint,
    seat_number varchar(255),
    status varchar(255) check (status in ('AVAILABLE','RESERVED','BOOKED')),
    primary key (id)
);

alter table if exists booking
    add constraint FK7ryitbom1ln9okwlj2t9tt9ym foreign key (seat_id) references seat;

alter table if exists seat
    add constraint FK3ovym176pe1oxrr87flc9ojcq foreign key (event_id) references event;